### ISSUE TITLE
Toast Container's width set to screen width makes it not possible for element to the side to be pressed

### ISSUE THREAD

**Issue by itsramiel** [arnnis/react-native-toast-notifications#147]
### Current behaviour

Toast Container's width set to screen width makes it not possible for element to the side to be pressed

### Expected behaviour

Components next to the toast, but not underneath should be pressable

### Code sample
Here is a repro https://github.com/itsramiel/toast-bug-repro

### Screenshots (if applicable)

https://user-images.githubusercontent.com/80689446/179970723-0920ebf2-3ba1-48ed-b4d6-ce66f1107ff2.mp4

### What have you tried
This bug was introduced by #140 #135 
remove setting the width propery. I will submit a pr to fix this

**Comment by pajkho** [comment]
Any news on this? We would really need a fix merged in as well.

**Comment by tsalama** [comment]
Still facing this issue. The three linked PRs aren't fully working for me. https://github.com/arnnis/react-native-toast-notifications/pull/148 and https://github.com/arnnis/react-native-toast-notifications/pull/168 don't work for me while https://github.com/arnnis/react-native-toast-notifications/pull/165 works, but then prevents the toast from showing in some of my screens.

**Comment by netojose** [comment]
2024 and the error still happens here
