### ISSUE TITLE
Refactor request(ToastProps): add width control to main container

### ISSUE THREAD

**Issue by alexandre1921** [arnnis/react-native-toast-notifications#157]
First of all, I was trying  to get my toast in the left of the page and I could achive this using at ToastProvider props

 `
style: {
     alignSelf: 'flex-start' as FlexAlignType,
},
`

![image](https://user-images.githubusercontent.com/44145981/204041556-6ae56749-f0f6-4070-b357-4324a43b8ee2.png)

But as you can see when you execute, the toast container gets in front of the content of my page, thereby my users wouldn't be able to use a button for example, I noticed that if you remove the width from the container you can access the content behind, so I would appreciate if there is a way to set the width of the container.

**Comment by arnnis** [comment]
This is fixed in version [3.4.0](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.4.0). Now it's possible to click on elements under the container.

**Comment by alexandre1921** [comment]
I still having issues with the elements under the container. Only updating the package don't resolve this issue, do I need to add something to my code? @arnnis

**Comment by arnnis** [comment]
> I still having issues with the elements under the container. Only updating the package don't resolve this issue, do I need to add something to my code? @arnnis 

I tested in the example app and it was working. (Only tested on android and web).

Please check the example app. If that not fixed your issue, let me know your react-native version and platform.

**Comment by chengjwk** [comment]
It is still failing for me (react-native-web: 0.18.12, running 3.4.0)
