### ISSUE TITLE
SafeAreaView not working on IOS

### ISSUE THREAD

**Issue by algarcia-vector** [arnnis/react-native-toast-notifications#160]
### Current behaviour
My toast is showing on my status bar on ios.

### Expected behaviour
My toast should display below my status bar.

### Code sample

```
import {SafeAreaView} from 'react-native';

      <ToastProvider
        renderType={{
          success: toast => (
            <SafeAreaView style={{flex: 1}}>
              <View style={styles.topContainer}>
                <View style={styles.leftContainer}>
                  <SuccessfullAlertIcon />
                </View>
                <View style={styles.rightContainer}>
                  <View style={styles.titleContainer}>
                    <View style={styles.positionTitle}>
                      <Text style={styles.titleText}>{toast.data}</Text>
                    </View>
                    <TouchableOpacity
                      style={styles.iconContainer}
                      onPress={() => {
                        toast.onHide();
                      }}>
                      <BlackCrossIcon />
                    </TouchableOpacity>
                  </View>
                  <View style={styles.subTitleContainer}>
                    <Text style={styles.message}>{toast.message}</Text>
                  </View>
                </View>
              </View>
            </SafeAreaView>
          ),
        }}>
      </ToastProvider>
```

### Screenshots (if applicable)

<img width="355" alt="Screen Shot 2022-11-30 at 16 23 50" src="https://user-images.githubusercontent.com/80910100/204921338-90b346b9-87f2-4be6-8932-4b74e031c075.png">

### What have you tried

I tried to wrap it in a SafeAreaView, but it did not work.

### Your Environment

| software                         | version |
| -------------------------------- | ------- |
| ios                   | 15.2
| react-native                     |0.68.2
| react-native-toast-notifications |3.3.1
| node                             |17.9.0
| npm or yarn                      |8.5.5

**Comment by algarcia-vector** [comment]
I was able to fix this problem by wrapping first a SafeAreaView then a View, both with flex: 1.

it's working like this:
```
export function Navigation() {
  const {accessToken} = useSelector((state: RootState) => state.login);
  return (
    <SafeAreaView style={{flex: 1}}>
      <View style={{flex: 1}}>
        <ToastProvider
          renderType={{
            success: toast => (
              <View style={styles.subMainContainer}>
                <View style={styles.topContainer}>
                  <View style={styles.leftContainer}>
                    <SuccessfullAlertIcon />
                  </View>
                  <View style={styles.rightContainer}>
                    <View style={styles.titleContainer}>
                      <View style={styles.positionTitle}>
                        <Text style={styles.titleText}>{toast.data}</Text>
                      </View>
                      <TouchableOpacity
                        style={styles.iconContainer}
                        onPress={() => {
                          toast.onHide();
                        }}>
                        <BlackCrossIcon />
                      </TouchableOpacity>
                    </View>
                    <View style={styles.subTitleContainer}>
                      <Text style={styles.message}>{toast.message}</Text>
                    </View>
                  </View>
                </View>
              </View>
            ),
          }}>
          {!accessToken ? <LoginStack /> : <MainStack />}
        </ToastProvider>
      </View>
    </SafeAreaView>
  );
}
```

**Comment by eleversa** [comment]
This solution has not worked for me. Has anyone managed to make the top toast look correctly in ios?

**Comment by donaldkwong** [comment]
I got it to render correctly by first using `react-native-safe-area-context` to get the safe top and bottom insets and then using those insets as values for the `offsetTop` and `offsetBottom` properties of the `ToastContainer`.

**Comment by eleversa** [comment]
@donaldkwong This sounds good. Finally, I have solved it using this fork: https://github.com/arnnis/react-native-toast-notifications/pull/167 (**fix safeareaview issue with toast notifications on notch devices**)

**Comment by arnnis** [comment]
This should be fixed in the new [ version 3.4.0](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.4.0)

**Comment by jmada** [comment]
> This should be fixed in the new [ version 3.4.0](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.4.0)

I've updated the library to that version and I'm still facing the same problem. :(
